//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumnoEjemplos.Socketes {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public float camaraOffsetHeight {
            get {
                return ((float)(this["camaraOffsetHeight"]));
            }
            set {
                this["camaraOffsetHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-400")]
        public float camaraOffsetForward {
            get {
                return ((float)(this["camaraOffsetForward"]));
            }
            set {
                this["camaraOffsetForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AlumnoMedia\\Socketes\\")]
        public string mediaFolder {
            get {
                return ((string)(this["mediaFolder"]));
            }
            set {
                this["mediaFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Texturas\\")]
        public string textureFolder {
            get {
                return ((string)(this["textureFolder"]));
            }
            set {
                this["textureFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pelota1.jpg")]
        public string textureBall {
            get {
                return ((string)(this["textureBall"]));
            }
            set {
                this["textureBall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cancha1.jpg")]
        public string textureField {
            get {
                return ((string)(this["textureField"]));
            }
            set {
                this["textureField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Textures\\uvw.png")]
        public string textureTeam1 {
            get {
                return ((string)(this["textureTeam1"]));
            }
            set {
                this["textureTeam1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Textures\\uvwGreen.png")]
        public string textureTeam2 {
            get {
                return ((string)(this["textureTeam2"]));
            }
            set {
                this["textureTeam2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkeletalAnimations\\Robot\\")]
        public string meshFolderPlayer {
            get {
                return ((string)(this["meshFolderPlayer"]));
            }
            set {
                this["meshFolderPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Robot-TgcSkeletalMesh.xml")]
        public string meshFilePlayer {
            get {
                return ((string)(this["meshFilePlayer"]));
            }
            set {
                this["meshFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Caminando-TgcSkeletalAnim.xml")]
        public string animationWalkFilePlayer {
            get {
                return ((string)(this["animationWalkFilePlayer"]));
            }
            set {
                this["animationWalkFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Correr-TgcSkeletalAnim.xml")]
        public string animationRunFilePlayer {
            get {
                return ((string)(this["animationRunFilePlayer"]));
            }
            set {
                this["animationRunFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parado-TgcSkeletalAnim.xml")]
        public string animationStopFilePlayer {
            get {
                return ((string)(this["animationStopFilePlayer"]));
            }
            set {
                this["animationStopFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parado")]
        public string animationStopPlayer {
            get {
                return ((string)(this["animationStopPlayer"]));
            }
            set {
                this["animationStopPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Correr")]
        public string animationRunPlayer {
            get {
                return ((string)(this["animationRunPlayer"]));
            }
            set {
                this["animationRunPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Caminando")]
        public string animationWalkPlayer {
            get {
                return ((string)(this["animationWalkPlayer"]));
            }
            set {
                this["animationWalkPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tribuna\\TribunaPopular-TgcScene.xml")]
        public string meshFileTribunePo {
            get {
                return ((string)(this["meshFileTribunePo"]));
            }
            set {
                this["meshFileTribunePo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arco\\Arco-Separado-TgcScene.xml")]
        public string meshFileGoal {
            get {
                return ((string)(this["meshFileGoal"]));
            }
            set {
                this["meshFileGoal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tribuna\\TribunaPlatea-TgcScene.xml")]
        public string meshFileTribunePl {
            get {
                return ((string)(this["meshFileTribunePl"]));
            }
            set {
                this["meshFileTribunePl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Audio\FIFA 1998 - Blur - Song 2.mp3</string>
  <string>Audio\FIFA World Cup 1998 - Chumbawamba - Tubthumping.mp3</string>
  <string>Audio\FIFA 1999 - Fatboy Slim - The Rockafeller Skank.mp3</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection music {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["music"]));
            }
            set {
                this["music"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\\\picadito.png")]
        public string picadito1 {
            get {
                return ((string)(this["picadito1"]));
            }
            set {
                this["picadito1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\\\picadito-seleccionado.png")]
        public string picadito2 {
            get {
                return ((string)(this["picadito2"]));
            }
            set {
                this["picadito2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\\\controles.png")]
        public string controles1 {
            get {
                return ((string)(this["controles1"]));
            }
            set {
                this["controles1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\\\controles-seleccionado.png")]
        public string controles2 {
            get {
                return ((string)(this["controles2"]));
            }
            set {
                this["controles2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\\\salir.png")]
        public string salir1 {
            get {
                return ((string)(this["salir1"]));
            }
            set {
                this["salir1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\\\salir-seleccionado.png")]
        public string salir2 {
            get {
                return ((string)(this["salir2"]));
            }
            set {
                this["salir2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\\\panel-controles.png")]
        public string panelcontroles {
            get {
                return ((string)(this["panelcontroles"]));
            }
            set {
                this["panelcontroles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("piso1.jpg")]
        public string textureFloor {
            get {
                return ((string)(this["textureFloor"]));
            }
            set {
                this["textureFloor"] = value;
            }
        }
    }
}
