//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumnoEjemplos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public float camaraOffsetHeight {
            get {
                return ((float)(this["camaraOffsetHeight"]));
            }
            set {
                this["camaraOffsetHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-600")]
        public float camaraOffsetForward {
            get {
                return ((float)(this["camaraOffsetForward"]));
            }
            set {
                this["camaraOffsetForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Media\\")]
        public string mediaFolder {
            get {
                return ((string)(this["mediaFolder"]));
            }
            set {
                this["mediaFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Texturas\\")]
        public string textureFolder {
            get {
                return ((string)(this["textureFolder"]));
            }
            set {
                this["textureFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pelota.jpg")]
        public string textureBall {
            get {
                return ((string)(this["textureBall"]));
            }
            set {
                this["textureBall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("red.jpg")]
        public string textureNet {
            get {
                return ((string)(this["textureNet"]));
            }
            set {
                this["textureNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cancha.jpg")]
        public string textureField {
            get {
                return ((string)(this["textureField"]));
            }
            set {
                this["textureField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uvw.jpg")]
        public string textureTeam1 {
            get {
                return ((string)(this["textureTeam1"]));
            }
            set {
                this["textureTeam1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uvwGreen.jpg")]
        public string textureTeam2 {
            get {
                return ((string)(this["textureTeam2"]));
            }
            set {
                this["textureTeam2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkeletalAnimations\\Robot\\")]
        public string meshFolderPlayer {
            get {
                return ((string)(this["meshFolderPlayer"]));
            }
            set {
                this["meshFolderPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Textures\\")]
        public string meshTextureFolder {
            get {
                return ((string)(this["meshTextureFolder"]));
            }
            set {
                this["meshTextureFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Robot-TgcSkeletalMesh.xml")]
        public string meshFilePlayer {
            get {
                return ((string)(this["meshFilePlayer"]));
            }
            set {
                this["meshFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Caminando-TgcSkeletalAnim.xml")]
        public string animationWalkFilePlayer {
            get {
                return ((string)(this["animationWalkFilePlayer"]));
            }
            set {
                this["animationWalkFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Correr-TgcSkeletalAnim.xml")]
        public string animationRunFilePlayer {
            get {
                return ((string)(this["animationRunFilePlayer"]));
            }
            set {
                this["animationRunFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parado-TgcSkeletalAnim.xml")]
        public string animationStopFilePlayer {
            get {
                return ((string)(this["animationStopFilePlayer"]));
            }
            set {
                this["animationStopFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parado")]
        public string animationStopPlayer {
            get {
                return ((string)(this["animationStopPlayer"]));
            }
            set {
                this["animationStopPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Correr")]
        public string animationRunPlayer {
            get {
                return ((string)(this["animationRunPlayer"]));
            }
            set {
                this["animationRunPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Caminando")]
        public string animationWalkPlayer {
            get {
                return ((string)(this["animationWalkPlayer"]));
            }
            set {
                this["animationWalkPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("people.jpg")]
        public string texturePeople {
            get {
                return ((string)(this["texturePeople"]));
            }
            set {
                this["texturePeople"] = value;
            }
        }
    }
}
