//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumnoEjemplos.Socketes {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public float camaraOffsetHeight {
            get {
                return ((float)(this["camaraOffsetHeight"]));
            }
            set {
                this["camaraOffsetHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-400")]
        public float camaraOffsetForward {
            get {
                return ((float)(this["camaraOffsetForward"]));
            }
            set {
                this["camaraOffsetForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Socketes\\")]
        public string mediaFolder {
            get {
                return ((string)(this["mediaFolder"]));
            }
            set {
                this["mediaFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Texturas\\pelota1.jpg")]
        public string textureBall {
            get {
                return ((string)(this["textureBall"]));
            }
            set {
                this["textureBall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Texturas\\cancha1.jpg")]
        public string textureField {
            get {
                return ((string)(this["textureField"]));
            }
            set {
                this["textureField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Textures\\uvw.png")]
        public string textureTeam1 {
            get {
                return ((string)(this["textureTeam1"]));
            }
            set {
                this["textureTeam1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkeletalAnimations\\Robot\\")]
        public string meshFolderPlayer {
            get {
                return ((string)(this["meshFolderPlayer"]));
            }
            set {
                this["meshFolderPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Robot-TgcSkeletalMesh.xml")]
        public string meshFilePlayer {
            get {
                return ((string)(this["meshFilePlayer"]));
            }
            set {
                this["meshFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Caminando-TgcSkeletalAnim.xml")]
        public string animationWalkFilePlayer {
            get {
                return ((string)(this["animationWalkFilePlayer"]));
            }
            set {
                this["animationWalkFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Correr-TgcSkeletalAnim.xml")]
        public string animationRunFilePlayer {
            get {
                return ((string)(this["animationRunFilePlayer"]));
            }
            set {
                this["animationRunFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parado-TgcSkeletalAnim.xml")]
        public string animationStopFilePlayer {
            get {
                return ((string)(this["animationStopFilePlayer"]));
            }
            set {
                this["animationStopFilePlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parado")]
        public string animationStopPlayer {
            get {
                return ((string)(this["animationStopPlayer"]));
            }
            set {
                this["animationStopPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Correr")]
        public string animationRunPlayer {
            get {
                return ((string)(this["animationRunPlayer"]));
            }
            set {
                this["animationRunPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Caminando")]
        public string animationWalkPlayer {
            get {
                return ((string)(this["animationWalkPlayer"]));
            }
            set {
                this["animationWalkPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tribuna\\TribunaPopular-TgcScene.xml")]
        public string meshFileTribunePo {
            get {
                return ((string)(this["meshFileTribunePo"]));
            }
            set {
                this["meshFileTribunePo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arco\\Arco-Separado-TgcScene.xml")]
        public string meshFileGoal {
            get {
                return ((string)(this["meshFileGoal"]));
            }
            set {
                this["meshFileGoal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tribuna\\TribunaPlatea-TgcScene.xml")]
        public string meshFileTribunePl {
            get {
                return ((string)(this["meshFileTribunePl"]));
            }
            set {
                this["meshFileTribunePl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Audio\FIFA 1998 - Blur - Song 2.mp3</string>
  <string>Audio\FIFA World Cup 1998 - Chumbawamba - Tubthumping.mp3</string>
  <string>Audio\FIFA 1999 - Fatboy Slim - The Rockafeller Skank.mp3</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection music {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["music"]));
            }
            set {
                this["music"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\picadito.png")]
        public string texturePicadito1 {
            get {
                return ((string)(this["texturePicadito1"]));
            }
            set {
                this["texturePicadito1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\picadito-seleccionado.png")]
        public string texturePicadito2 {
            get {
                return ((string)(this["texturePicadito2"]));
            }
            set {
                this["texturePicadito2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\controles.png")]
        public string textureControles1 {
            get {
                return ((string)(this["textureControles1"]));
            }
            set {
                this["textureControles1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\controles-seleccionado.png")]
        public string textureControles2 {
            get {
                return ((string)(this["textureControles2"]));
            }
            set {
                this["textureControles2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\salir.png")]
        public string textureSalir1 {
            get {
                return ((string)(this["textureSalir1"]));
            }
            set {
                this["textureSalir1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\salir-seleccionado.png")]
        public string textureSalir2 {
            get {
                return ((string)(this["textureSalir2"]));
            }
            set {
                this["textureSalir2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu\\panel-controles.png")]
        public string texturePanelcontroles {
            get {
                return ((string)(this["texturePanelcontroles"]));
            }
            set {
                this["texturePanelcontroles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Texturas\\piso1.jpg")]
        public string textureFloor {
            get {
                return ((string)(this["textureFloor"]));
            }
            set {
                this["textureFloor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Textures\\uvwGreen.png")]
        public string textureTeam2 {
            get {
                return ((string)(this["textureTeam2"]));
            }
            set {
                this["textureTeam2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Texturas\\canchaMenu.jpg")]
        public string textureMenuField {
            get {
                return ((string)(this["textureMenuField"]));
            }
            set {
                this["textureMenuField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Texturas\\wall-texture.jpg")]
        public string textureWall {
            get {
                return ((string)(this["textureWall"]));
            }
            set {
                this["textureWall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBox\\11.png")]
        public string textureSkyFacesUp {
            get {
                return ((string)(this["textureSkyFacesUp"]));
            }
            set {
                this["textureSkyFacesUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBox\\22.png")]
        public string textureSkyFaceDown {
            get {
                return ((string)(this["textureSkyFaceDown"]));
            }
            set {
                this["textureSkyFaceDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBox\\33.png")]
        public string textureSkyFaceLeft {
            get {
                return ((string)(this["textureSkyFaceLeft"]));
            }
            set {
                this["textureSkyFaceLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBox\\55.png")]
        public string textureSkyFaceRight {
            get {
                return ((string)(this["textureSkyFaceRight"]));
            }
            set {
                this["textureSkyFaceRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBox\\44.png")]
        public string textureSkyFaceFront {
            get {
                return ((string)(this["textureSkyFaceFront"]));
            }
            set {
                this["textureSkyFaceFront"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBox\\66.png")]
        public string textureSkyFaceBack {
            get {
                return ((string)(this["textureSkyFaceBack"]));
            }
            set {
                this["textureSkyFaceBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poste\\Poste-TgcScene.xml")]
        public string meshFilePoste {
            get {
                return ((string)(this["meshFilePoste"]));
            }
            set {
                this["meshFilePoste"] = value;
            }
        }
    }
}
